.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.31.0 */

/* Handwritten function */
glabel func_803002D0
    /* 12D0 803002D0 18A00011 */  blez       $a1, .L80300318
    /* 12D4 803002D4 00000000 */   nop
    /* 12D8 803002D8 240B4000 */  addiu      $t3, $zero, 0x4000
    /* 12DC 803002DC 00AB082B */  sltu       $at, $a1, $t3
    /* 12E0 803002E0 1020000F */  beqz       $at, .L80300320
    /* 12E4 803002E4 00000000 */   nop
    /* 12E8 803002E8 00804021 */  addu       $t0, $a0, $zero
    /* 12EC 803002EC 00854821 */  addu       $t1, $a0, $a1
    /* 12F0 803002F0 0109082B */  sltu       $at, $t0, $t1
    /* 12F4 803002F4 10200008 */  beqz       $at, .L80300318
    /* 12F8 803002F8 00000000 */   nop
    /* 12FC 803002FC 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* 1300 80300300 310A001F */  andi       $t2, $t0, 0x1F
    /* 1304 80300304 010A4023 */  subu       $t0, $t0, $t2
  .L80300308:
    /* 1308 80300308 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* 130C 8030030C 0109082B */  sltu       $at, $t0, $t1
    /* 1310 80300310 1420FFFD */  bnez       $at, .L80300308
    /* 1314 80300314 25080020 */   addiu     $t0, $t0, 0x20
  .L80300318:
    /* 1318 80300318 03E00008 */  jr         $ra
    /* 131C 8030031C 00000000 */   nop
  .L80300320:
    /* 1320 80300320 3C088000 */  lui        $t0, 0x8000
    /* 1324 80300324 010B4821 */  addu       $t1, $t0, $t3
    /* 1328 80300328 2529FFE0 */  addiu      $t1, $t1, -0x20
  .L8030032C:
    /* 132C 8030032C BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* 1330 80300330 0109082B */  sltu       $at, $t0, $t1
    /* 1334 80300334 1420FFFD */  bnez       $at, .L8030032C
    /* 1338 80300338 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* 133C 8030033C 03E00008 */  jr         $ra
.size func_803002D0, . - func_803002D0
